### ISSUE TITLE
DataGrid.RowSelectable not firing when clicking the DataGridMultiSelectColumn checkbox directly

### ISSUE THREAD

**Issue by christophwille** [Megabit/Blazorise#2531]
I have a DataGrid defined with RowSelectable. The event fires fine when I click somewhere on the row, however, when directly clicking the checkbox it doesn't fire. 

I am using the bog-standard DataGridMultiSelectColumn:

`<DataGridMultiSelectColumn TItem="FileInfoShortened" Width="30px"></DataGridMultiSelectColumn>`

**Comment by David-Moreira** [comment]
This behaviour is fixed with version 0.9.4 which is now in preview. 
With the introdution of ShiftClick support to select multiple rows, the feature was slightly reworked, to be closer to how regular click works. PR #2151

However I do think it's worth fixing this behaviour on 0.9.3. I also found out that using the checkbox to Select All Rows also does not honor this behaviour.
@stsrki will most likelly provide 2 PRs.
- One that patches this behaviour specifically on 0.9.3 for a regular checkbox click.
- One that patches the behaviour when the select all checkbox is clicked. (This one can then be merged or cherry picked to 0.9.4)
  - I'm not sure how you handle multiple version PRs, just let me know if this is fine.

**Comment by geersjake** [comment]
I am still having this issue in 9.4.3 and it can be seen in the live demo as well (assuming it was upgraded). Am I missing something?

```razor
<DataGrid TItem="Employee"
          Data="_employeeList"
          Editable="false"
          Sortable="false"
          Resizable="true"
          Filterable="true"
          ShowPager="true"
          Striped="true"
          Bordered="true"
          Hoverable="true"
          UseInternalEditing="false"
          Narrow="true"
          ShowPageSizes="true"
          PageSize="_pageSize"
          PageSizeChanged="OnPageSizeChanged"
          SelectionMode="DataGridSelectionMode.Multiple"
          SelectedRows="_selectedEmployees"
          SelectedRowsChanged="SelectedRowsChanged">
    <DataGridColumns>
        <DataGridMultiSelectColumn TItem="Employee" Width="30px"></DataGridMultiSelectColumn>
...
```
