### ISSUE TITLE
Problem with Layout After Blazorise Update

### ISSUE THREAD

**Issue by stevenlupo** [Megabit/Blazorise#2754]
Something happened to the layout with the latest update to Blazorize. It's as if the `LayoutHeader` isn't there and everything got pushed up. 

I tried to upload a screenshot but Github keeps erroring when I try.

**Comment by stsrki** [comment]
We fixed it already and it will be available in 0.9.4.2.

**Comment by stevenlupo** [comment]
I just upgraded to 0.9.4.2 and nothing has changed, I still have this problem.

**Comment by stsrki** [comment]
Refresh your app with ctrl+f5. We changed JS files that sometimes get cached by the browser. In that doesn't work please post full code to reproduce the issue on our side.

**Comment by hammie1010** [comment]
I couldn't get the layout to display correct either.  In this example, if you comment out the footer in MainLayout, it'll work.  With the footer it won't.  https://github.com/hammie1010/WebApplication1.git

**Comment by stevenlupo** [comment]
@hammie1010 I tried that with my own project and it was still broken.

There's definitely something still wrong. I did the ctrl+F5 thing, and still no luck.

**Comment by hammie1010** [comment]
> @hammie1010 I tried that with my own project and it is still broken.
> 
> There's definitely something still wrong. I did the ctrl+F5 thing, and still no luck.

I agree, something still off when it tries to calculate the bar height.

**Comment by stevenlupo** [comment]
@hammie1010 I tried out your code. If you take the code out of `MainFooter.razor` and paste it directly into `MainLayout.razor` instead, the problem goes away, but I don't understand why. It's the same behavior I'm experiencing though, that is, the content is getting pushed up. But I'm not using a razor component in my `LayoutFooter`, yet I still have the problem--even if I comment out the `LayoutFooter `entirely.

**Comment by stevenlupo** [comment]
@hammie1010 I figured it out! -- sort of. _Remove_ the `Fixed="true"` from the `LayoutHeader` and it will work regardless of what's in the `LayoutFooter`.

```
    <LayoutHeader Fixed="true">
        <MainMenu></MainMenu>
    </LayoutHeader>
```

I also duplicated this in my own project: if I remove `Fixed="true"`, the problem goes away! But I don't understand _why_ this is the case.

**Comment by hammie1010** [comment]
> @hammie1010 I figured it out! -- sort of. _Remove_ the `Fixed="true"` from the `LayoutHeader` and it will work regardless of what's in the `LayoutFooter`.
> 
> ```
>     <LayoutHeader Fixed="true"> @* remove Fixed=true *@
>         <MainMenu></MainMenu>
>     </LayoutHeader>
> ```
> 
> I also duplicated this in my own project: if I remove `Fixed="true"`, the problem goes away! But I don't understand _why_ this is the case.

Yeah - original issue was https://github.com/Megabit/Blazorise/issues/2695

**Comment by stsrki** [comment]
I have tried your layout structure on the Blazorise demo and cannot reproduce it on my side. Here is my screenshot

![image](https://user-images.githubusercontent.com/900302/128087986-94e24610-c3f1-457d-852e-eefa3b1693ac.png)

**Comment by hammie1010** [comment]
> I have tried your layout structure on the Blazorise demo and cannot reproduce it on my side. Here is my screenshot
> 
> ![image](https://user-images.githubusercontent.com/900302/128087986-94e24610-c3f1-457d-852e-eefa3b1693ac.png)

What happens if you just clone my project?

**Comment by stsrki** [comment]
Aaaaaahhh I found the problem. You have two horizontal `Bar`'s. One for the top and one for the footer section. I never expected to have a second horizontal Bar. So in this case that second, or footer bar is overriding the top bar height calculation. And since it is smaller the page content will be behind the top bar.

Now that I know what is the problem I can easily fix it.

**Comment by stsrki** [comment]
Guys, can you try RC from MyGet? https://github.com/Megabit/Blazorise#try-preview

I want to make sure it is OK before I release it on nuget.

**Comment by stevenlupo** [comment]
Just updated to 0.9.4.3-rc1 and I still have the problem in my project. Did hard-refreshes with ctrl+f5.

**Comment by stevenlupo** [comment]
Wait a sec... I got the package from https://www.myget.org/F/blazorise/api/v3/index.json

There isn't anything on https://github.com/Megabit/Blazorise#try-preview

Did I get the right package?

**Comment by stsrki** [comment]
https://www.myget.org/F/blazorise/api/v3/index.json should be the right source.

**Comment by stevenlupo** [comment]
I just figured out what I was doing that caused the problem in my project: I had a nested `Layout` for some reason (see below). I removed the nesting and it worked. I have to adjust the padding a bit now, not sure how it ended up that way. I discovered it because it worked in the sample project @hammie1010 gave.

This is what I had:
```
<Layout>
    <LayoutHeader Fixed="true">
        <MainMenu></MainMenu>
    </LayoutHeader>
    <Layout>
        <Layout>
            <LayoutContent>
                @Body
            </LayoutContent>
        </Layout>
    </Layout>
    <LayoutFooter Fixed="true">
        <MainFooter></MainFooter>
    </LayoutFooter>
</Layout>
```

**Comment by hammie1010** [comment]
> Guys, can you try RC from MyGet? https://github.com/Megabit/Blazorise#try-preview
> 
> I want to make sure it is OK before I release it on nuget.

I still have the same issue if I update to 0.9.4.3-rc1 in my example progject.  Ctrl+F5 didn't resolve.

**Comment by stsrki** [comment]
I'm also trying to reproduce it with collapsed and expanded menu when minimized and then resize the browser. All seems to work.

**Comment by hammie1010** [comment]
> @hammie1010 I don't understand, because I tried your project with the new RC and it worked.

One way to trying to repo: When you start running the site, look at the size of the top and bottom bar.  The bottom bar will be smaller.  If I grab the lower right corner of the browser and move it, suddenly the bottom bar size matches the top bar.

**Comment by stevenlupo** [comment]
> > @hammie1010 I don't understand, because I tried your project with the new RC and it worked.
> 
> One way to trying to repo: When you start running the site, look at the size of the top and bottom bar. The bottom bar will be smaller. If I grab the lower right corner of the browser and move it, suddenly the bottom bar size matches the top bar.

Yes, I see it too.

**Comment by hammie1010** [comment]
> > > @hammie1010 I don't understand, because I tried your project with the new RC and it worked.
> > 
> > 
> > One way to trying to repo: When you start running the site, look at the size of the top and bottom bar. The bottom bar will be smaller. If I grab the lower right corner of the browser and move it, suddenly the bottom bar size matches the top bar.
> 
> Yes, I see it too.

The other way to repo is to start the site, make the width small enough to collapse the top bar, expand the menu, and click on a link in it, and then widen the page back.

**Comment by stevenlupo** [comment]
This is what happens when I do that:

![image](https://user-images.githubusercontent.com/4267021/128183167-19bbde02-298b-4821-b6b6-8d57243e6fe9.png)

**Comment by stsrki** [comment]
I should make a different approach to fix this. I Will let you know how it goes.

**Comment by hammie1010** [comment]
> 0.9.4.3-rc2 released, so try again.
> 
> I realized a major flaw with Bar theming. By settings:
> 
> ```cs
> BarOptions = new()
>         {
>             HorizontalHeight = "72px"
>         },
> ```
> 
> the CSS variable `--b-bar-horizontal-height` will be set. But the problem is that it will be used by ALL horizontal Bars. Which is wrong. I will need to figure how to best handle that scenario.

Update to 0.9.4.3-rc2, the behavior is the same.

**Comment by stsrki** [comment]
OK, guys, I want to give you an update on what I did and what are your options. I was trying to come up with a non-breaking solution since yesterday but without luck. So I reverted everything to where we started and made just a small adjustment so that at least it doesn't break too much.

---

As I already said, Theme HorizontalHeight was always meant to be used for only one Bar, which is placed at the top, inside of LayoutHeader. And according to that, I have made some changed so that the Bar in the footer would not be affected.

Also, I removed bar height calculations as it was basically not possible to make it work with collapse mode. At least for now in 0.9.4, without changing API, there is no way to fix it.

---

This all leads us to this. **Setting Theme HorizontalHeight is required!** This is a must. Or set the `--b-bar-horizontal-height` through CSS if theming is not possible.

@hammie1010 I tried your test app with the latest changes (HorizontalHeight manually set) and it works as expected.

**Comment by guillermodimas** [comment]
> @hammie1010 I tried your test app with the latest changes (HorizontalHeight manually set) and it works as expected.

I tried this and it does fixed the Layout placement, but there's still an overlay preventing any buttons/links from the LayoutContent from being pressed.

**Comment by guillermodimas** [comment]
Any updates on this?

**Comment by stsrki** [comment]
Should be done with the 0.9.4.3 release from yesterday.
