### ISSUE TITLE
Divider in Bootstrap 5

### ISSUE THREAD

**Issue by stevenlupo** [Megabit/Blazorise#3228]
The Divider in Bootstrap5 does not display properly.

Try:

`<Divider DividerType=@DividerType.TextContent Text="some text goes here" />`

and you will get the line but the text blurred in the middle of the page.

**Comment by muratyuceer** [comment]
Same here

**Comment by stsrki** [comment]
It should be fixed in the latest 0.9.5.2. https://github.com/Megabit/Blazorise/commit/32a62d5f0d01fab1af9cb82b8311929a8ae57f76

Can you check your project references? Also, clear the cache with Ctrl+F5.

**Comment by stevenlupo** [comment]
This is not fixed. I'm using 0.9.5.2. I emptied the cache and did a hard reload.

I'm not sure what you mean by check project references, what should I be checking?

**Comment by stsrki** [comment]
@stevenlupo By project reference, I meant to check that all your projects are using 0.9.5.x version. We got a lot of folks coming from the ABP framework with similar issues and problems often that ABP internally is still using an older version of Blazorise. If that is not the case you can ignore it.

BTW, can you post the screenshot of the divider?

**Comment by stevenlupo** [comment]
I only use Blazorise in one project, so project references are okay.

Here's a screenshot that shows the text in the center of the page, yet the horizontal line is at the top.
![image](https://user-images.githubusercontent.com/4267021/146778499-f287f902-cd05-4207-926e-793d2141602f.png)

Here's the entire code for the page:
![image](https://user-images.githubusercontent.com/4267021/146778529-ec733ff4-e4a5-43f5-8b0b-bb496de3f2e3.png)

**Comment by stsrki** [comment]
That's weird truly. Can you inspect in dev tools to see what else in your CSS might affect the divider position?

**Comment by stevenlupo** [comment]
I'm not seeing anything leap out at me.

Are you saying if you use the exact code, it displays correctly?

**Comment by stevenlupo** [comment]
here's a screenshot of the generated html.
![image](https://user-images.githubusercontent.com/4267021/146779905-03e838fb-2b59-4d24-93d8-b5fd29544d5d.png)

here's a snapshot of the css on the hr element, maybe you can see something:
![image](https://user-images.githubusercontent.com/4267021/146780180-4ad2d174-cc62-4aac-abfb-ae74b27db557.png)

**Comment by stsrki** [comment]
You're right there is something wrong. In my tests, it worked well. But if I write only those same components as you have then it breaks.
